import json
import urllib.request

def create_pull_request(repo_name: str, branch_name: str, title: str, token: str, org: str) -> str:
    """Creates a PR using GitHub's REST API."""
    url = f"https://api.github.com/repos/{org}/{repo_name}/pulls"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }
    data = {
        "title": title,
        "head": branch_name,
        "base": "main",
        "body": "Automated PR generated by ADK Terraform Agent."
    }
    
    req = urllib.request.Request(url, data=json.dumps(data).encode('utf-8'), headers=headers, method='POST')
    try:
        with urllib.request.urlopen(req) as response:
            res_data = json.loads(response.read().decode())
            return res_data['html_url']
    except Exception as e:
        raise Exception(f"Failed to create PR. Ensure your token has repo scopes. Error: {e}")